// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoYojLeyBa448LJE3cistwR9_PtEc8rdM',
    appId: '1:1076773390327:web:eff6ae25036b6d0be050f2',
    messagingSenderId: '1076773390327',
    projectId: 'todo-25b6d',
    authDomain: 'todo-25b6d.firebaseapp.com',
    storageBucket: 'todo-25b6d.firebasestorage.app',
    measurementId: 'G-4VVZ64TZSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbHBaSsn-Rcnz9DEuw3kl3v_3x3o-dYf8',
    appId: '1:1076773390327:android:58b6b3698355c938e050f2',
    messagingSenderId: '1076773390327',
    projectId: 'todo-25b6d',
    storageBucket: 'todo-25b6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnBuxKFtVnKiSmKxkiyqgTdcWFl7buPWw',
    appId: '1:1076773390327:ios:b19abbcfd5a4b84de050f2',
    messagingSenderId: '1076773390327',
    projectId: 'todo-25b6d',
    storageBucket: 'todo-25b6d.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnBuxKFtVnKiSmKxkiyqgTdcWFl7buPWw',
    appId: '1:1076773390327:ios:b19abbcfd5a4b84de050f2',
    messagingSenderId: '1076773390327',
    projectId: 'todo-25b6d',
    storageBucket: 'todo-25b6d.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoYojLeyBa448LJE3cistwR9_PtEc8rdM',
    appId: '1:1076773390327:web:1b471b9a98168713e050f2',
    messagingSenderId: '1076773390327',
    projectId: 'todo-25b6d',
    authDomain: 'todo-25b6d.firebaseapp.com',
    storageBucket: 'todo-25b6d.firebasestorage.app',
    measurementId: 'G-XLC69JPKZY',
  );
}
